### ISSUE TITLE
option sameSite is invalid - Quickstart tutorial not working

### ISSUE THREAD

**Issue by JonPawelko** [auth0-samples/auth0-express-webapp-sample#21]
I run the Quickstart guide or similar tutorial... https://www.youtube.com/watch?v=QQwo4E_B0y8
and get the "option sameSite is invalid" error in my browser that appears to be somewhat common.  Auth0 docs has some recommendations including installing Caddy, but there has to be an easier solution.  I have a practically brand new computer with all recent versions of software and can't run the simple Auth0 demo out of the box.

**Comment by adamjmcgrath** [comment]
Hi @JonPawelko 

> option sameSite is invalid

This is expected behaviour and should not cause you issues beyond that message. We set 2 cookies to workaround the [SameSite changes introduced to newer browsers](https://developers.google.com/search/blog/2020/01/get-ready-for-new-samesitenone-secure). One cookie is for legacy browsers and one for newer browsers

> Browsers implementing the newer behavior will set the cookie with the SameSite value, while other browsers may ignore or incorrectly set it. However, those same browsers will set the legacy cookie (the one that is causing that error in your browser). When processing included cookies, the SDK first checks for the presence of the new style cookie and if it's not found, then fallback to the legacy cookie.
https://web.dev/samesite-cookie-recipes/#handling-incompatible-clients

You can disable this by setting `legacySameSiteCookie` to `false` https://auth0.github.io/express-openid-connect/interfaces/configparams.html#legacysamesitecookie but be aware that this may cause your website not to work in older browsers (listed here https://www.chromium.org/updates/same-site/incompatible-clients)
